# Generated by Django 5.0 on 2024-01-28 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulas',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
