# Generated by Django 5.0 on 2024-01-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_formulas_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulas',
            new_name='Formula',
        ),
    ]
