# Generated by Django 5.0 on 2026-01-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_formulas_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulas',
            name='users',
        ),
    ]
