# Generated by Django 5.0 on 2024-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
