# Generated by Django 5.0 on 2024-01-16 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auth',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Название статьи'),
        ),
    ]
