# Generated by Django 5.0 on 2024-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
